frontend/src/Router.tsx, frontend/src/component/FileList.tsx, frontend/src/component/FileMenu.tsx, frontend/src/component/LoginComponent.tsx, frontend/src/component/Sidebar.tsx, frontend/src/component/SignupComponent.tsx, frontend/src/page/LoginPage.tsx, frontend/src/page/MainPage.tsx, frontend/src/page/SignupPage.tsx
메인페이지와 로그인 페이지의 레이아웃을 개발함.
이후, 라우팅 처리를 하였음
=> 레이아웃 작업 완료

backend/bin/www, backend/package-lock.json, backend/package.json, backend/src/app.ts, backend/src/model/cloud.ts, backend/src/model/index.ts, backend/src/model/user.ts, frontend/src/App.tsx
Mongoose를 설치하고 프로젝트의 Schema를 적용했습니다.
#10
=> [Feat] Mongoose 설치 및 Schema 적용

frontend/package-lock.json, frontend/package.json, frontend/src/component/Header.tsx, frontend/src/component/LoginComponent.tsx, frontend/src/component/SignupComponent.tsx, package-lock.json, package.json
=> 로그인, 회원가입 유효성 검사 및 모달 구현

script/deploy.sh
docker compose의 버전차이로 인한 명령어 변경
=> [Fix] docker compose 버전 문제 해결

backend/package-lock.json, backend/package.json, backend/src/DTO/index.ts, backend/src/DTO/user.ts, backend/src/app.ts, backend/src/config/passport.ts, backend/src/routes/index.ts, backend/src/routes/user.ts, frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/Router.tsx, frontend/src/component/LoginComponent.tsx, frontend/src/component/SignupComponent.tsx
=> 새로고침시 로그인을 유지하도록 수정함

backend/src/DTO/capacity.ts, backend/src/DTO/index.ts, backend/src/DTO/user.ts, backend/src/route/auth.ts, backend/src/route/user.ts, backend/src/service/cloud/capacity.ts, backend/src/service/cloud/index.ts, backend/src/service/index.ts, frontend/src/model/user.ts
- 특정 사용자의 현재/최대 용량을 반환하는 함수 구현
- 특정 사용자의 현재 용량을 증가/감소하는 함수 구현
- validate 함수 역시 구현함
- 특정 사용자의 최대 용량을 변경하는 함수 구현
- 특정 사용자의 현재/최대 용량을 보내주는 API 구현
- 기존의 User DTO에서 Capacity를 분리함
- 분리하는 것이 좋은지에 대해서는 더 고민해볼 필요가 있음
=> 사용자의 현재/최대 용량을 수정/조회하는 기능 구현

.gitignore, backend/package-lock.json, backend/package.json, backend/src/app.ts, backend/src/middleware/index.ts, backend/src/middleware/multer.ts, backend/src/middleware/passport.ts, backend/src/route/auth.ts, backend/src/route/cloud.ts, backend/src/route/index.ts, backend/src/route/user.ts
multer를 사용하여 백엔드 서버에서 파일 업로드 API를 구현함
TODO: DB에 실제 파일 및 메타데이터 저장
=> 서버의 파일 업로드 api 구현

frontend/src/Router.tsx, frontend/src/component/Sidebar.tsx, frontend/src/model/capacity.ts, frontend/src/model/index.ts, frontend/src/page/MainPage.tsx, frontend/src/util/capacity.ts
서버로부터 현재 로그인된 사용자의 현재/최대 용량을 받아온다.
이후, 뷰에 렌더링하여 보여줌
=> 사용자의 현재/최대 사용량 조회 UI 구현

backend/src/route/user.ts, backend/src/service/cloud/directory.ts, backend/src/service/cloud/index.ts
현재 디렉토리의 파일 리스틑 받아오는 API를 구현했습니다.
=> [Feat] 파일 리스트 API 구현

frontend/src/component/DropBox.tsx, frontend/src/component/FileMenu.tsx
드롭박스를 통해 파일 업로드/ 폴더 업로드를 선택할 수 있음
=> 파일 업로드시 드롭박스 추가

frontend/src/asset/style/theme.ts, frontend/src/component/Header.tsx
=> 페이지 레이아웃 수정

frontend/src/App.tsx, frontend/src/DTO/file.ts, frontend/src/component/Button.tsx, frontend/src/component/File.tsx, frontend/src/component/FileList.tsx, frontend/src/component/FileMenu.tsx, frontend/src/page/MainPage.tsx
=> 파일 선택 기능 추가

frontend/src/App.tsx, frontend/src/asset/style/theme.ts, frontend/src/component/Header.tsx
=> 로그아웃 기능 구현

frontend/src/asset/style/global-styles.ts, frontend/src/asset/style/styled.d.ts, frontend/src/asset/style/theme.ts, frontend/src/asset/style/type.d.ts
폰트 : Gmarket Sans
스타일:
- 패딩
- 헤더 : 좌우 40px, 상하 20px?(상하는 적절히 조절해보자)
- 본문 : 20px
- 모달 : 20px
- Font Family
- GMarket Sans
- 폰트 크기
- 본문 : 16px
- 제목 : 18px
- 대표색
- 헤더 배경 : #e4ebf1 rgb(228,235,241)
- Primary Color: #084A83
- 컨텐츠 색 : #282828
- 메타데이터 색 : #888888
- 선 및 Progress Bar Background : #d7d7d7
- 기본 백그라운드 : #fff
- 서브 백그라운드 : #f6f6f6
- 선택된 파일
- 드롭박스 등
- 모달창 백그라운드 : rgba(196, 196, 196, 0.5)
- 포인트 색 (노랑) : #f3aa18
=> 공통 스타일 및 폰트 적용

backend/src/service/cloud/directory.ts, frontend/src/component/fileManagement/File.tsx, frontend/src/component/fileManagement/FileList.tsx, frontend/src/page/MainPage.tsx, frontend/src/util/date.ts, frontend/src/util/index.ts
- 파일 리스트의 스크롤 기능이 적용되지 않던 버그를 수정하고, 스타일을 변경함
- 폴더 이름 우측의 여백을 클릭해도 이동하던 버그를 수정함
- 파일 선택후 디렉토리 이동 시, 선택 상태가 유지되던 버그를 수정함
- 파일의 메타데이터의 포맷을 변경함
=> 버그 수정 및 스타일 변경

backend/src/service/cloud/directory.ts, frontend/src/component/fileManagement/FileIcon.tsx
- 파일리스트 요청 API를 수정했습니다.
- 필요없는 인자 제거
- 폴더의 경우 올바른 디렉토리 반환
- 파일 아이콘 오류 수정
- text 파일이 올바른 아이콘으로 렌더링되도록 수정
=> 파일 리스트 요청 API  및 파일 아이콘 오류 수정

frontend/src/component/LoginComponent.tsx, frontend/src/component/SignupComponent.tsx, frontend/src/page/LoginPage.tsx, frontend/src/page/SignupPage.tsx
=> [Refactor] 로그인, 회원가입 모달창 변경

frontend/src/component/DirectoryList/DirectoryList.tsx, frontend/src/page/MainPage.tsx
쓰레기통 페이지에 있을 경우 정상작동하지 않던 버그를 수정함
=> 사이드바 디렉토리 리스트의 네비게이션이 정상작동하도록 수정

backend/src/route/cloud.ts, backend/src/service/cloud/download.ts
- 파일 다운로드가 정상적으로 작동하지 않는 문제 수정
- 파일 깊이에 따른 루트 디렉토리 재설정
=> [Fix] 파일이 정상적으로 다운로드 되지 않는 문제 수정

backend/src/route/cloud.ts
기존의 비동기 로직은 for await of를 사용했다.
이 때문에, 각각의 for루프가 동기적으로 동작하여 성능이 좋지 않았다.
이를 Promise.all로 변경하여 for 루프 내부가 비동기적으로 동작하게 했다.
=> 파일 업로드의 비동기 로직 수정

frontend/src/component/fileManagement/File.tsx, frontend/src/component/fileManagement/FileList.tsx, frontend/src/component/fileManagement/FileMenuForMain.tsx, frontend/src/component/fileManagement/FileMenuForTrash.tsx, frontend/src/component/fileManagement/Selection.tsx, frontend/src/page/MainPage.tsx, frontend/src/page/TrashPage.tsx, frontend/src/util/throttle.ts
- 파일을 선택 혹은 선택해제 하는 작업의 성능을 개선함
- Map 자료구조를 이용하여 삽입, 삭제에 필요한 비용을 줄임으로써 성능을 개선하였음.
- 드래그 박스를 그려주는 작업의 성능을 개선함
- Throttle을 적용함으로써 작업이 일어나는 횟수를 조절해 성능을 개선하였음.
=> 성능 개선을 위한 리팩토링 진행

backend/src/service/cloud/directory.ts
=> [Refactor] 특정 디렉토리의 리스트를 불러오는 API 수정

backend/src/route/cloud.ts, backend/src/service/cloud/download.ts, frontend/src/component/hook/useContextMenu.ts
선택하지 않은 파일을 다운로드 하는 버그를 수정했습니다.
삭제된 파일을 다운로드하는 버그를 수정했습니다.
=> [Fix] 다운로드 API 수정

backend/package-lock.json, backend/src/DTO/cloud.ts, backend/src/model/cloud.ts, backend/src/route/cloud.ts, backend/src/route/user.ts, backend/src/service/cloud/directory.ts, backend/src/service/cloud/file.ts, frontend/src/DTO/cloud.ts, frontend/src/DTO/file.ts, frontend/src/Router.tsx, frontend/src/component/DirectoryList/DirectoryList.tsx, frontend/src/component/HeaderContextMenu.tsx, frontend/src/component/fileManagement/File.tsx, frontend/src/component/fileManagement/FileForStar.tsx, frontend/src/component/fileManagement/FileList.tsx, frontend/src/component/fileManagement/FileListForStar.tsx, frontend/src/component/fileManagement/FileMenuForMain.tsx, frontend/src/component/fileManagement/FileMenuForStar.tsx, frontend/src/component/fileManagement/NewFolderModal.tsx, frontend/src/component/hook/useContextMenu.ts, frontend/src/page/StarPage.tsx, frontend/src/util/file.ts
- 중요 문서함 추가 구현
- 중요 문서함 삭제 구현
- 중요 문서함 페이지 구현
- 중요 문서함에서 다운로드 구현
=> 중요 문서함 기능 추가 구현

backend/src/route/cloud.ts, backend/src/service/cloud/file.ts, frontend/src/asset/style/global-styles.ts, frontend/src/component/common/ContextDropdown.tsx, frontend/src/component/common/ContextMenu.tsx, frontend/src/component/fileManagement/MoveFileModal.tsx, frontend/src/page/MainPage.tsx
- 우클릭 드롭박스의 스타일을 수정함
- 파일 이동 모달의 스타일을 수정함
- 버튼 엘리먼트에 마우스를 올리면, 커서 모양을 변경하도록 함
=> 대략적인 스타일 수정

frontend/src/component/fileManagement/FileMenuForMain.tsx, frontend/src/component/fileManagement/NewFolderModal.tsx, frontend/src/util/file.ts
- 중복 검사 로직 분리
- 새 폴더 생성 시 폴더명 검사
=> 중복된 이름으로 새 폴더 생성 방지 기능 구현

backend/src/DTO/cloud.ts, backend/src/route/cloud.ts, backend/src/service/cloud/file.ts, backend/src/service/cloud/index.ts, backend/src/service/cloud/update.ts, frontend/src/api/moveFile.ts, frontend/src/component/fileManagement/FileMenuForMain.tsx, frontend/src/component/fileManagement/FileMenuForStar.tsx, frontend/src/component/fileManagement/FileMenuForTrash.tsx, frontend/src/component/fileManagement/MoveFileModal.tsx, frontend/src/util/index.ts, frontend/src/util/regex.ts
- 폴더 및 파일 이동시, 타겟 폴더에 중복된 이름이 있는지 확인 후 변경함
=> 폴더 경로 이동 구현

frontend/src/component/layout/Header.tsx
=> 로그아웃 모달 레이아웃 수정

backend/src/route/cloud.ts, backend/src/route/user.ts, frontend/src/util/file.ts
=> [Refactor] 백엔드 리팩토링
